---
title: "Rock Medicine"
---

## What is Rock Medicine?

Rock Medicine is a volunteer-based event medicine organization that has provided free, non-judgmental medical care at California's largest concerts and festivals for over 50 years. Originally founded in partnership with the Haight Ashbury Free Clinics in the 1970s, Rock Med was built on the idea that high-quality care should be available without cost or judgment.

Rock Med aims to treat and support patients in a way with priority placed on getting them home safely. They do not involve billing, insurance, or unnecessary emergency department visits.

At each event, teams are composed of licensed physicians, nurses, EMTs, paramedics, PAs, NPs, and trained CPR volunteers. Most events operate with Advanced Life Support (ALS) capabilities, and volunteers treat a wide range of trauma and medical calls, from minor injuries to altered mental status. Rock Med is typically first on scene within the venue, and coordinates with 911 when hospital transport is necessary.

### Venues Near Berkeley
- UC Berkeley’s Greek Theatre
- Bill Graham Civic Auditorium
- Fox Theater (Oakland)
- Golden Gate Park
- Oracle Park

### Some Events They Cover
- Outside Lands
- BottleRock
- Aftershock
- 49ers games at Levi’s Stadium (and the Superbowl)

## Why Should BMRC Members Join?
- Counts toward the EMS engagement requirement for BMRC members
- Offers first on scene patient care experience at large-scale events
- Emphasizes a non-judgmental, patient-first model of care that many EMS jobs do not
- Flexible with your schedule, no minimum volunteering requirement
- Provides the opportunity to learn from experienced ALS providers in a collaborative setting
- Requires no prior experience to start, they will prepare you to lead calls
- Volunteers can learn how to dispatch teams and become show leads 

While BMRC is not officially affiliated with Rock Medicine, many of our members are active Rock Med volunteers, and we highly encourage participation.
BMRC has a Slack channel for travel coordination, and members often carpool or take public transit to events together. Most events run from late spring through fall.

## How to Join

- [**Sign up**](https://www.rockmed.org/volunteer-join/)
- [**FAQs**](https://www.rockmed.org/volunteer-join/#FAQs)

After completing the application, you'll be able to create an account and sign up for available shifts.

---

_To submit a Rock Medicine event towards your EMS engagement requirement, fill out [this form](insert)_
